version: '3.1'

services:
  springboot:
    image: 790120743628.dkr.ecr.eu-north-1.amazonaws.com/ecr-spingboot-mongo-docker:VERSION
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - mycustomnetwork  

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - mycustomnetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  mycustomnetwork:
    external: true
